"""add columns to table

Revision ID: 976036b27b59
Revises: 0a5346711181
Create Date: 2024-04-02 21:49:13.012573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976036b27b59'
down_revision = '0a5346711181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
